### ISSUE TITLE
How to dismiss the tutorial ?

### ISSUE THREAD

**Issue by Hugoo** [hyperoslo/Presentation#106]
Hi !

Thanks for this great library !
I'm trying to implement it at the opening of my app but at the end of the tutorial, I want to change the "next" button with a "Close" button or something like that (or putting a big "Start using the app" button in the middle of the screen"...)

Do you have any hints on how to do that ?

Thanks !

**Comment by vadymmarkov** [comment]
Hi @Hugoo, you can set `presentationDelegate` on `PresentationController` and then in `didSetViewController:atPage` change `presentationController.navigationItem.rightBarButtonItem` on the last page.

**Comment by Hugoo** [comment]
Hi @vadymmarkov, thank you for your answer and sorry for my late reply. I managed to do it with your indications thanks !
