### ISSUE TITLE
Demo with parallax scrolling

### ISSUE THREAD

**Issue by vadymmarkov** [hyperoslo/Presentation#36]
It's about the demo I've presented today. Have 2 questions to discuss:
- What is the best name for it - Parallax, ParallaxSlides, MagicMove or something else?
- Should we add a mark in the name that it's iPad only demo (related to both demos we have)?
- Do we need to put some text on the each slide or that's enough to have jsut images, animations and so on?

**Comment by zenangst** [comment]
I think `Parallax` is a good name for that kind of presentation. It's essentially when you have multiple layers that move at different speeds to great a 2D effect.

I think we could make different demos, showing different things. One could be a presentation, one could be release notes, a tutorial and a magazine.

**Comment by vadymmarkov** [comment]
@zenangst Ok, then will go with `Parallax`. But do we need some text there?

**Comment by zenangst** [comment]
@vadymmarkov text for the slides?

**Comment by vadymmarkov** [comment]
@zenangst Yes. I can leave the text on the slides you've seen today during my presentation, or we can change it, or just drop it and show only images and nice animations.

**Comment by zenangst** [comment]
You could rename the thing to Parallax and make a presentation about what the effect is.
You can use wikipedia as a source for the slides : http://en.wikipedia.org/wiki/Parallax

**Comment by vadymmarkov** [comment]
Good idea!

**Comment by 3lvis** [comment]
Fixed by the amazing :star2:  @vadymmarkov :star2: !
