### ISSUE TITLE
Possibility to add different positions for portrait/landscape

### ISSUE THREAD

**Issue by vadymmarkov** [hyperoslo/Presentation#43]
Probably we have to use size classes here.

**Comment by vadymmarkov** [comment]
Now we have `Position(left: 0.3, right: 0.4)` (wrapper around constraints) to place view or animation. But things could be different for landscape and portrait, so maybe there should be the possibility to apply orientation-specific positioning. 

@zenangst @3lvis What do you guys think?

**Comment by 3lvis** [comment]
I think that would work but ideally `Presentation` should figure out and just make it work.

(Hehehe, I know, not so helpful, but I think that's how it should work)

**Comment by vadymmarkov** [comment]
Now `Presentation` applies the same constraints for both landscape and portrait and in most of the cases it works well. But when you have many images I think it's useful to have more control.

**Comment by zenangst** [comment]
@vadymmarkov Is this still an issue?

**Comment by vadymmarkov** [comment]
@zenangst Not really :smiley:

**Comment by zenangst** [comment]
:tada:
