### ISSUE TITLE
Smaller gif in README

### ISSUE THREAD

**Issue by RamonGilabert** [hyperoslo/Presentation#48]
Even with Safari in full size I cannot see the full screen, I feel with that gif you cannot appreciate all the work that the pod contains, I'd do it a bit smaller, what do you think?

**Comment by zenangst** [comment]
Yah, it's a bit big, I guess @vadymmarkov went big and then went home *giggle*

**Comment by vadymmarkov** [comment]
Ok, guys, I'll make it smaller :smile:
