### ISSUE TITLE
Bug: animation glitch / improper scrolling behavior

### ISSUE THREAD

**Issue by richardoti** [hyperoslo/Presentation#54]
Run a demo, then:
steps to reproduce the bug:
1. Press Next Page or scroll to the next / previous page
2. While application keeps inertial scrolling (fingers are off the screen), try to touch and scroll text label only. You have to be fast.
3. After view has scrolled to the other page, try to scroll it again. You'll see the glitch.

Start: 
![screen shot 2015-06-10 at 10 29 58](https://cloud.githubusercontent.com/assets/8013017/8078151/b69dc3d2-0f5b-11e5-91c5-e2a3f1651d1c.png)
Pay attention to the positions of background objects on the screen.

Before glitch:
![screen shot 2015-06-10 at 10 30 04](https://cloud.githubusercontent.com/assets/8013017/8078180/f4e5e016-0f5b-11e5-8e2a-d7b8a6010e91.png)

The positions of the background objects are the same, while label has scrolled to another one. If you try to touch screen and scroll after, you'll see the glitch.

Issue is reproducible in both of demos.

**Comment by richardoti** [comment]
I've spent quite a time on debugging this issue and found out that the problem is in UIPageViewController's scrollView. Each time scrollview changes active page, it resets content offset to be equal to the screen width.

Also, if next/previous buttons are pressed multiple times in a row, scrollview provides false values of its offset, so it is impossible to use some kind of accumulator and store real offset.

The only solution I see here is to remove UIPageViewController and swap it with UIScrollView / UICollectionView

**Comment by kostiakoval** [comment]
The same issue! OMG, I was struggling with that a lot. It's an auto layout constraints issue

**Comment by kostiakoval** [comment]
It should work fine in iOS 9, seems like iOS bug.

**Comment by richardoti** [comment]
@kostiakoval Hmm I cannot see an AutoLayout issues, but the issue with UIPageViewController. I would be happy if they've fixed it. UIPageViewController uses somehow different scrollView than the standard one, it automatically resets itself to zero after scrolling to the next page.

**Comment by kostiakoval** [comment]
@richardoti  Here is what I've seen. I've created an simple View Controller in storyboard, (without setting constraints). It works fine
When I set constraints manually (to the Top layout guide) than I start getting this issue.

**Comment by richardoti** [comment]
@kostiakoval Interesting. Would like to take a look at your example.

**Comment by kostiakoval** [comment]
Have a look on the Pages storyboard example.
