### ISSUE TITLE
Documentation should specify the pod install for the demos

### ISSUE THREAD

**Issue by GabrielAlva** [hyperoslo/Presentation#58]
Hi,
For new cocoaPods users it would be good if you specified on the readMe to run the pod install to run the demo projects. Great project by the way!

**Comment by 3lvis** [comment]
@GabrielAlva You can always use `pod try Presentation`.

https://github.com/hyperoslo/Presentation/pull/59

**Comment by vadymmarkov** [comment]
@GabrielAlva I was also improved in https://github.com/hyperoslo/Presentation/pull/59 and https://github.com/hyperoslo/Presentation/pull/63. So I guess we could close it.
