### ISSUE TITLE
Vertical transitions don't work with gestures

### ISSUE THREAD

**Issue by ipranay** [hyperoslo/Presentation#64]
Hi... awesome library!

I was just playing with this and found that in the tutorial example if you used something like this:
```
    presentationController.addAnimations([
        TransitionAnimation(content: content1, destination: Position(left: 0.3, top: 0.2)),
        TransitionAnimation(content: content2, destination: Position(right: 0.4, top: 0.22)),
        TransitionAnimation(content: content3, destination: Position(left: 0.5, top: 0.6))
      ], forPage: 1)
```
...which is simply adding a vertical transition to the third image. And then add similar code for the other pages as well.

It works if you press the next and previous buttons, but the image gets stuck when using the swipe gestures.
Although, if you change it to horizontal transitions, it works fine.

**Comment by vadymmarkov** [comment]
@ipranay Thanks for feedback. We'll take a look at it.
