### ISSUE TITLE
Not compatible with Swift 2.0

### ISSUE THREAD

**Issue by davemen** [hyperoslo/Presentation#66]
This looks AMAZING. I really want to use it for my latest project but it's got a few issues working with Swift 2.0. I can try to fix it but wondering if you guys are already on it?

**Comment by vadymmarkov** [comment]
@davemen We're planning to do a migration to Swift 2.0 soon, but if you're able to help us with that, it would be awesome! We could have a separate branch for 2.0, so feel free to make a PR.

**Comment by kostiakoval** [comment]
The presentation uses Pages as a dependency. 
Pages now is upgraded to Swift 2.0
https://github.com/hyperoslo/Pages/tree/swift_2.0

**Comment by zenangst** [comment]
@davemen should be ready to go now :tada:

**Comment by davemen** [comment]
Sweet! Thank you!!
