### ISSUE TITLE
How should I do after called goTo: app freeze for a little while

### ISSUE THREAD

**Issue by macbaszii** [hyperoslo/Presentation#79]
I put a skip button on every screen to go to particular screen.
goTo(index:) will be called when I press the skip button.

Nevertheless, the screen will freeze for a little while after the screen come.
I have to wait a bit then I can scroll back to previous screen.

Do I miss something ?
Thanks in advance.

**Comment by macbaszii** [comment]
Solved, I have to set maxAnimationDelay myself.
Please close, Thanks.

**Comment by zenangst** [comment]
@macbaszii awesome that you found a solution for this! 👍
