### ISSUE TITLE
Button not tappable 

### ISSUE THREAD

**Issue by droidery** [hyperoslo/Presentation#89]
I tried adding a tappable UIButton to the example in `configureBackground()`. It doesn't work as `addToBackground` is taking the touch events.

Same issue as in https://stackoverflow.com/questions/24814401/uibutton-targets-not-working-if-a-uiview-is-added-as-a-subview

**Comment by vadymmarkov** [comment]
@droidery If you add any `SlideController`'s, their views are above everything you add to the background. You can try to set `userInteractionEnabled` to `false` on `SlideController`'s view, but I am not sure if it's what you want to achieve.

**Comment by maxydon** [comment]
I fixed this buy the button's content's view to the top of the view hierarchy

**Comment by vadymmarkov** [comment]
Cool @maxydon. Then I think I'm going to close this one.
