### ISSUE TITLE
How can I use autolayout with this library?

### ISSUE THREAD

**Issue by fmaylinch** [hyperoslo/Presentation#93]
Hi,

How can I use autolayout with this library? I see the doc and example apps are hardcoding the view frames, while the content positioning is relative (with percentages). How can I combine these two different approaches?

If it's possible, can you add examples in the doc and example apps? If it's not, can you add support for it?

What I've been doing is hardcoding the frames too, and calculating the percentage they represent relative to the view (i.e. to the screen). That way I can combine those calculated percentages and the percentages that Position objects expect.

For example, let's say I add an image and set a frame size of 200 x 100 points. Then I calculate the size percentage to the screen width and height, which let's suppose it's 0.5 x 0.2. Then say I position this image at `Position(left:0.6, top:0.4)`. Now I can, for example, add another image aligned to the top-center the first one. Since the image is positioned at 0.4 vertically, and it's height relation is 0.2, the top would be at 0.4 - 0.2/2 = 0.3, so the top center would be at `Position(left:0.6, top:0.3)`. The calculation is easy but it would be great if the library could do this for you.

Any help will be appreciated. Thank you!

**Comment by vadymmarkov** [comment]
We love autolayout, but I'm afraid it will add extra complexity to the library when it comes to positioning and animations. If you have an idea of how to implement it in a good way we would be happy to review your PR and discuss it further.
