### ISSUE TITLE
Hi do a swift 4 version is on schedule ?

### ISSUE THREAD

**Issue by Coriolan-Bataille** [hyperoslo/Presentation#94]
Hi Presentation Teams.
I would like to know if you're going to update, and if yes when, the actual version of Presentation.
I wish you good day !
And thx in advance for an answer !

**Comment by vadymmarkov** [comment]
Hi @Coriolan-Bataille! Swift 4 version is released https://github.com/hyperoslo/Presentation/releases/tag/4.0.0
