### ISSUE TITLE
add '@objc' to expose this instance method to Objective-C

### ISSUE THREAD

**Issue by arunabhdas** [hyperoslo/Presentation#95]
Getting the following error while building with this library

[12:19:43]: ▸ <...>/Pods/Presentation/Source/PresentationController.swift:112:8: note: add '@objc' to expose this instance method to Objective-C
[12:19:43]: ▸   func updateAnimationTimer(_ timer: Timer) {
[12:19:43]: ▸        ^
[12:19:43]: ▸   @objc 

Build Env is as follows : 

+-------------+----------------------------------------------------------+
|                           Build environment                            |
+-------------+----------------------------------------------------------+
| xcode_path  | <...>/Xcode/Xcode_9_0_0/Xcode_9_0_0.app |
| gym_version | 2.58.0                                                   |
| sdk         | iPhoneOS11.0.sdk                                         |
+-------------+----------------------------------------------------------+

**Comment by vadymmarkov** [comment]
@arunabhdas Can you test it with Swift 4 version? https://github.com/hyperoslo/Presentation/releases/tag/4.0.0

**Comment by vadymmarkov** [comment]
Should be fixed in 4.0.0.
