### ISSUE TITLE
Declarations in extensions cannot override yet

### ISSUE THREAD

**Issue by arunabhdas** [hyperoslo/Presentation#98]
Getting the following error on line 31 of PresentationController.swift

> `Ambiguous use of 'add'`

and the following error on line 122 of PresentationController.swift 

> `Declarations in extensions cannot override yet`

Function add is as below : 

```
// MARK: - Content

extension PresentationController {

  open override func add(_ viewControllers: [UIViewController]) {
    for case let controller as SlideController in viewControllers  {
      slides.append(controller)
    }
    super.add(viewControllers)
  }

```

Using Swift 3.2 language version in Xcode 9.2

**Comment by vadymmarkov** [comment]
It should be fixed in Swift 4 release.
